const APP_CONFIG = {
  // ซ่อน Key ด้วยการเข้ารหัส Base64 (ป้องกัน GitHub แบน Key)
  GDRIVE_CLIENT_ID: atob('MTQwMDAzMTgzMDg2LWdpbTE4MDI1YnZjMGJxNDIwamFiZ2Zva2YxcWdhaWpuLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t'),
  GDRIVE_API_KEY: atob('QUl6YVN5Q210UnNPRWJZcmpZVVVIZHhqRDUyeVZoYXd2WndpUDU4'),

  GROQ_API_KEY: atob('Z3NrX2NzcG1tTWR3TDRlV2ROY3JubWp2V0dkeWIzRllUVGJ6QWNqTWl0U3ZLRzF1Z1BJRUZ0NTc='),

  GEMINI_API_KEY: atob('QUl6YVN5RDI5Q1VPbEQ0YkF4WWlwRGZPWE9iM1laNG9LMkNSdms4')
};
